// "use client"
import localFont from "next/font/local";
import 'bootstrap/dist/css/bootstrap.min.css';
import "./globals.css";
// import { usePathname } from 'next/navigation';
import Navbar from "@/components/Navbar";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  // const pathname = usePathname();

  // const backgroundColors = {
  //   '/': 'bg-bg1',
  //   '/about': 'bg-blue-100',
  //   '/contact': 'bg-green-100',
  // };
  // const pageBgClass = backgroundColors[pathname] || 'bg-white';
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-bg1`}
      >
         {/* <div className={`${pageBgClass}`}>
          <Navbar />
          {children}
        </div> */}
        {children}
      </body>
    </html>
  );
}
